title: tempo 문서
description: tempo 앱 문서 모음
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
color_scheme: light
search_enabled: true
aux_links:
  "GitHub 저장소":
    - "https://github.com/KalGookSoo/tempo"
